==== Dynamic Memory Allocation

===== new Keyword

[source, c++]
----
new int; // finds an address in memory with 4 bits in a row by checking the free list
----

* It takes time to find block of memory that is big enoug for our needs
* Returns a pointer
* Calls constructor
* Is an operator
* **new** will call `malloc()`

 new Entity := (Entity*) malloc(sizeof(Entity)) + constructor
 
* must use `delete` to free memory

===== malloc()

Memory allocation
[source, cpp]

----  
 int *tag = (int *) malloc(sizeof(int));
----

`malloc()` and `calloc()` return `void*` type and this allows these functions to be used to allocate memory of any data type (just because of `void*`) . In Cpp, we must explicitly typecast return value of `malloc()` to `(int *)`. Note that the below line without the typecast compiles in C, but doesn’t compile in Cpp.

[source, cpp]
----  
 int *tag = malloc(sizeof(int) * n);
----

===== new vs. malloc()

Following are the differences between `malloc()` and operator `new`:

1. Calling Constructors: `new` calls constructors, while `malloc()` does not. In fact primitive data types (char, int, float.. etc) can also be initialized with `new`. For example, below program prints 10.

[source, cpp]
----
int main()
{
   int *n = new int(10); // initialization with new()
   cout << *n;
   getchar();
   return 0;
}
----

2. operator vs function: `new` is an operator, while `malloc()` is a function.
3. return type: `new` returns exact data type, while `malloc()` returns void *.
4. Failure Condition: On failure, `malloc()` returns `NULL` where as new Throws.
5. Memory: In case of `new`, memory is allocated from free store where as in `malloc()` memory allocation is done from heap.
6. Overriding: We are allowed to override new operator where as we can not override the `malloc()` function legally.
7. Size: Required size of memory is calculated by compiler for `new`, where as we have to manually calculate size for `malloc()`.

.Table Title
|===
|new | malloc

|calls constructor
|doesnot calls constructors

|It is an operator
|It is a function

|Returns exact data type
|Returns `void*`

|on failure, Throws 	
|On failure, returns `NULL`

|Memory allocated from free store
|Memory allocated from heap

|can be overridden
|cannot be overridden

|size is calculated by compiler
|size is calculated manually

|use `delete` to free memory
|use `free()` to free memory

|===

Please write comments if you find anything incorrect in the above post, or you want to share more information about the topic discussed above.

===== delete and free()

In Cpp, delete operator should only be used either for the pointers pointing to the memory allocated using new operator or for a NULL pointer, and free() should only be used either for the pointers pointing to the memory allocated using malloc() or for a NULL pointer.

[source, c++]
----
int main()
{
    int x;
    int *ptr1 = &x;
    int *ptr2 = (int *)malloc(sizeof(int));
    int *ptr3 = new int;
    int *ptr4 = NULL;
 
    /* delete Should NOT be used like below because x is allocated 
        on stack frame */
    delete ptr1;  
 
    /* delete Should NOT be used like below because x is allocated 
        using malloc() */
    delete ptr2;  
 
    /* Correct uses of delete */
    free(ptr2);
    delete ptr3;
    delete ptr4;
 
    getchar();
    return 0;
}
----